# Generated by Django 5.0.7 on 2024-08-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('products', models.IntegerField(default=0)),
                ('items', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('brand', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('countInStock', models.SmallIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('items', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.products')),
            ],
            options={
                'verbose_name': 'Cart',
                'unique_together': {('userId', 'productId')},
            },
        ),
    ]
