# Generated by Django 5.0.7 on 2024-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
