# Generated by Django 5.0.7 on 2025-01-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_product_list_orders_products_relationship_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders_products_relationship',
            unique_together={('order', 'product')},
        ),
    ]
