# Generated by Django 5.0.7 on 2024-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_orders_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
