# Generated by Django 5.0.7 on 2025-01-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_orders_products_relationship_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='isShown',
        ),
    ]
