# Generated by Django 5.0.7 on 2024-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_orders_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='encode',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
