# Generated by Django 5.0.7 on 2025-01-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_orders_isshown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='division',
        ),
    ]
