# Generated by Django 5.0.7 on 2024-12-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_orders_encode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='isShown',
            field=models.BooleanField(default=False),
        ),
    ]
