# Generated by Django 5.0.7 on 2025-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_orders_isshown'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
    ]
