# Generated by Django 5.0.7 on 2025-01-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_products_rate_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
