# Generated by Django 5.0.7 on 2025-01-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_orders_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='show_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
