# Generated by Django 5.0.7 on 2025-01-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_user_address_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
