# Generated by Django 5.0.7 on 2025-01-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_orders_show_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='delivered_by',
            new_name='rider',
        ),
    ]
