# Generated by Django 5.0.7 on 2025-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_delivered_by_orders_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='user',
            name='apartment',
            field=models.CharField(default='None', max_length=1024),
        ),
    ]
